### ISSUE TITLE
Mixer implementation (Question) 

### ISSUE THREAD

**Issue by zeppelinux** [Trilarion/java-vorbis-support#3]
Hi,

I want to implement software mixer that can mix (volume/level change for each source should be supported) several ogg/vorbis files and create single OGG stream from them.  
Is java-vorbis-support a proper tool for this project? What would be high level sequence of steps in order to make it happen?

Thanks!

**Comment by Trilarion** [comment]
Maybe, but I wouldn't really know. For this project I just combined three already existing separate libraries into a single one. In the end, they implement the Java Sound API. If the [Java Sound API](https://www.oracle.com/java/technologies/java-sound-api.html) supports what you want to do then it may be possible but I would not know how. If not then it might not be possible or not as straightforward.
